[platformio]
data_dir = web

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32
board = esp32dev
board_build.filesystem = littlefs
framework = arduino
lib_archive = false
lib_deps =
	mathieucarbou/ESP Async WebServer @ ^3.0.6
	mathieucarbou/AsyncTCP @ ^3.3.2
	askuric/Simple FOC@^2.4.0
lib_ignore =
	AsyncTCP_RP2040W
	ESPAsyncTCP-esphome
	Async TCP
monitor_speed = 115200